### ISSUE TITLE
A little typo in the repository tag "awesome"

### ISSUE THREAD

**Issue by amivanoff** [w3c-cg/awesome-semantic-shapes#10]
A little typo in the repository tag "awesome"

Related to #7 and #8

**Comment by amivanoff** [comment]
@ianbjacobs , could you please help us one more time with this topic correction

**Comment by ianbjacobs** [comment]
Fixed (I think).

**Comment by tpluscode** [comment]
#8 is passing now. Thanks @ianbjacobs
