### ISSUE TITLE
give more people maintainer rights

### ISSUE THREAD

**Issue by VladimirAlexiev** [w3c-cg/awesome-semantic-shapes#2]
@simonstey could you please give committer (maintainer?) rights to @VladimirAlexiev @labra @HolgerKnublauch @tpluscode . The idea is for more people to be able to contribute directly, and approve PRs by others.
See https://github.com/w3c/shacl/issues/78 for a discussion and list of sources that we'll use to populate this.

**Comment by simonstey** [comment]
I don't have access to the repository settings /: @ianbjacobs can do that maybe?

**Comment by afs** [comment]
Is he a CG member?
He will need to have joined the SHACL community group, which includes agreeing to the contributors agreement.

**Comment by simonstey** [comment]
he invited me to this repo, that's why I /cc him ;)

**Comment by afs** [comment]
My bad - it was about the problem of assigning people. https://github.com/w3c/shacl/issues/78#issuecomment-2360176708
"he" = "@amivanoff"

AIUI This repo is under the SHACC CG so the IPR/sign-up from there applies.

**Comment by ianbjacobs** [comment]
Hi all, I've added the named people with committer access. If there are settings you'd like, let me know.

**Comment by amivanoff** [comment]
I joined the SHACL community group & signed the contributors agreement

**Comment by tpluscode** [comment]
Apparently, I never was member of SHACL CG. Wanted to join but I updated my affiliation and it is pending review. How long does it typically take? Can anyone expedite it?

**Comment by ianbjacobs** [comment]
Hi @tpluscode, I'll follow up with you separately on this.

**Comment by VladimirAlexiev** [comment]
- @simonstey I thought I saw you in the settings of that repo. sorry if I was mistaken!
- @tpluscode I think anyone can contribute through PRs even if not a member of the CG

**Comment by VladimirAlexiev** [comment]
I assume this is done
