### ISSUE TITLE
Possible relax of License and Contributors constraints

### ISSUE THREAD

**Issue by amivanoff** [w3c-cg/awesome-semantic-shapes#5]
1 The default repository stub has two licenses:
* [W3C Software and Document License](https://www.w3.org/copyright/software-license/) -- for all reports
* [W3C 3-clause BSD License](https://www.w3.org/copyright/3-clause-bsd-license-2008/) -- for Test Suites

It turns out, [pull request constraints](https://github.com/sindresorhus/awesome/blob/main/pull_request_template.md) in the "awesome list of awesomes" in the sindresorhus/awesome repo has these license statements, which prevents us from adding this repository to the "awesomes" list after its completion:
* _We strongly recommend the [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/), but any [Creative Commons license](https://creativecommons.org/choose/) will work._
* _A code license like MIT, BSD, Apache, GPL, etc, is not acceptable. Neither are WTFPL and [Unlicense](https://unlicense.org/)._

Is it possible to do all of this for this repository?
* To dump BSD for Test Suites, because there will be no Test Suites or any other source code?
* To use for the Readme file, Issues and Pull requests [CC0 license](https://creativecommons.org/publicdomain/zero/1.0/) or any other of CC license instead of W3C Software and Document License?

2 There is another constraint in [w3c-cg/awesome-semantic-shapes](https://github.com/w3c-cg/awesome-semantic-shapes) (if I understand it correctly) that a pull request author(s) should be strictly from the SHACL Community Group.

It is different from typical process in "awesomes" community where anyone could propose a pull request, but maintainers desides what to accept.

**Comment by VladimirAlexiev** [comment]
@ianbjacobs and @pchampin I am all for it!
Awesome lists are built collaboratively: people submit PRs.
Especially people who made something and want to advertise it in the list.
Asking them to sign contributor agreements will just turn them off.

This repo is "special" as w3c repos go: there's no spec here, just a crowd-sourced list of resources.

(PS: Ian, I cannot assign, would it be possible to allow me to?)

**Comment by ianbjacobs** [comment]
The [SHACL CG](https://www.w3.org/community/shacl/) is "chartered" to publish specifications. Therefore we expect to continue to ask for organizational licensing commitments for people joining the group.

If you want to accept contributions to this particular repo by non-participants, that is probably ok as long as that information does not go into a specification.

**Comment by VladimirAlexiev** [comment]
@ianbjacobs This is a crowd-sourced list of resources, it won't go into the specification.

**Comment by ianbjacobs** [comment]
@VladimirAlexiev, you can ask people to submit PRs to this repo, then, without requiring them to sign the CLA. 

@dontcallmedom, can you work with me to configure the repo so that the IPR checks don't happen?

**Comment by dontcallmedom** [comment]
I've removed the IPR bot from this repo
