### ISSUE TITLE
Add repository topics and description

### ISSUE THREAD

**Issue by amivanoff** [w3c-cg/awesome-semantic-shapes#7]
To discuss and then to implement:

1. Please add to the repository two mandatory topics `awesome` and `awesome-list`. Linter [awesome-lint](https://github.com/sindresorhus/awesome-lint) shows errors.

2. And maybe topics like `shacl` and `semantic-web` could be of help also.

3. Please, add the repository description `A curated list of Semantic Shapes resources` (or maybe we need to make description more detailed).

**Comment by VladimirAlexiev** [comment]
@ianbjacobs could you please do this: I cannot.
- topics: `awesome, awesome-list, shacl, shex, rdf-shapes`
- description: "A curated list of RDF Shape resources"

**Comment by ianbjacobs** [comment]
Done
